/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import java.awt.BorderLayout;

/**
 *
 * @author EDU
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setLocationRelativeTo(null);
        Home p1= new Home() ;
        p1.setSize(1820, 770);
        p1.setLocation(0,0);
        PestañadeVinculacion.removeAll();
        PestañadeVinculacion.add(p1, BorderLayout.CENTER);
        PestañadeVinculacion.revalidate();
        PestañadeVinculacion.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PestañadeVinculacion = new javax.swing.JPanel();

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnInicio = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        jButton1 = new javax.swing.JButton();
        btn_generarorden = new javax.swing.JButton();
        btn_report = new javax.swing.JButton();
        btn_venta = new javax.swing.JButton();
        btn_consultas = new javax.swing.JButton();
        btn_mantenimiento = new javax.swing.JButton();


        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PestañadeVinculacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout PestañadeVinculacionLayout = new javax.swing.GroupLayout(PestañadeVinculacion);
        PestañadeVinculacion.setLayout(PestañadeVinculacionLayout);
        PestañadeVinculacionLayout.setHorizontalGroup(
            PestañadeVinculacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1818, Short.MAX_VALUE)
        );
        PestañadeVinculacionLayout.setVerticalGroup(
            PestañadeVinculacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

            .addGap(0, 768, Short.MAX_VALUE)
        );

        getContentPane().add(PestañadeVinculacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 1820, 770));

        jLabel1.setText("numero de compra");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1720, 40, -1, -1));

        jLabel2.setText("hora");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1580, 50, -1, -1));

        jLabel3.setText("usuario");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 50, -1, -1));

        jMenu1.setText("Home");

        btnInicio.setText("Inicio");
        btnInicio.addActionListener(new java.awt.event.ActionListener() {

            .addGap(0, 798, Short.MAX_VALUE)
        );

        getContentPane().add(PestañadeVinculacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 129, 1420, 800));

        jButton1.setText("MENU");
        jButton1.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });

        jMenu1.add(btnInicio);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Mantenimiento");

        jMenuItem1.setText("Usuario");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Productos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Cliente");
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 180, 60));

        btn_generarorden.setText("GENERAR ORDEN");
        btn_generarorden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_generarordenActionPerformed(evt);
            }
        });
        getContentPane().add(btn_generarorden, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 180, 60));

        btn_report.setText("REPORTE");
        btn_report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reportActionPerformed(evt);
            }
        });
        getContentPane().add(btn_report, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, 180, 60));

        btn_venta.setText("VENTA");
        btn_venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ventaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 180, 60));

        btn_consultas.setText("CONSULTAS");
        btn_consultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultasActionPerformed(evt);
            }
        });
        getContentPane().add(btn_consultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 560, 180, 60));

        btn_mantenimiento.setText("MANTENIMIENTO");
        btn_mantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mantenimientoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_mantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 650, 180, 60));


        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        // TODO add your handling code here:
        Home p1= new Home() ;
        p1.setSize(1820, 770);
        p1.setLocation(0,0);
        PestañadeVinculacion.removeAll();
        PestañadeVinculacion.add(p1, BorderLayout.CENTER);
        PestañadeVinculacion.revalidate();
        PestañadeVinculacion.repaint();
    }//GEN-LAST:event_btnInicioActionPerformed


    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        Producto p3= new Producto() ;
        p3.setSize(1820, 770);

    private void btn_generarordenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_generarordenActionPerformed
        // TODO add your handling code here:
        compra p2= new compra();
        p2.setSize(1420, 950);
        p2.setLocation(0,0);
        PestañadeVinculacion.removeAll();
        PestañadeVinculacion.add(p2, BorderLayout.CENTER);
        PestañadeVinculacion.revalidate();
        PestañadeVinculacion.repaint();
    }//GEN-LAST:event_btn_generarordenActionPerformed

    private void btn_reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reportActionPerformed
        // TODO add your handling code here:
        otracosa p3= new otracosa();
        p3.setSize(1420, 950);

        p3.setLocation(0,0);
        PestañadeVinculacion.removeAll();
        PestañadeVinculacion.add(p3, BorderLayout.CENTER);
        PestañadeVinculacion.revalidate();
        PestañadeVinculacion.repaint();

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    }//GEN-LAST:event_btn_reportActionPerformed

    private void btn_ventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ventaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ventaActionPerformed

    private void btn_consultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_consultasActionPerformed

    private void btn_mantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mantenimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_mantenimientoActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PestañadeVinculacion;

    private javax.swing.JMenuItem btnInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;

    private javax.swing.JButton btn_consultas;
    private javax.swing.JButton btn_generarorden;
    private javax.swing.JButton btn_mantenimiento;
    private javax.swing.JButton btn_report;
    private javax.swing.JButton btn_venta;
    private javax.swing.JButton jButton1;

    // End of variables declaration//GEN-END:variables
}
