
package Paneles;


import FuncionamientoTablas.TablaCliente;
import Clases.Cliente;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author EQUIPO
 */
public class Clientes extends javax.swing.JPanel {

    Cliente pro=new Cliente();
    TablaCliente proDao=new TablaCliente();
    DefaultTableModel modelo = new DefaultTableModel();
    
    public Clientes() {
        initComponents();
        Listaclientes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_ruc = new javax.swing.JTextField();
        txt_id = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        txt_apellido = new javax.swing.JTextField();
        txt_dni = new javax.swing.JTextField();
        txt_telefono = new javax.swing.JTextField();
        txt_direccion = new javax.swing.JTextField();
        txt_estado = new javax.swing.JTextField();
        btn_agregar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_cliente = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setForeground(new java.awt.Color(255, 204, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel1.setText("Ruc Cliente");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 610, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel2.setText("Id Cliente");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel3.setText("Nombre");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel4.setText("Apellido");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel5.setText("DNI");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel6.setText("Teléfono");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel7.setText("Dirección");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel8.setText("Estado");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 540, -1, -1));
        jPanel1.add(txt_ruc, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 600, 240, 30));
        jPanel1.add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 240, 30));
        jPanel1.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 240, 30));
        jPanel1.add(txt_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 240, 30));
        jPanel1.add(txt_dni, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 240, 30));
        jPanel1.add(txt_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, 240, 30));
        jPanel1.add(txt_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 450, 240, 30));
        jPanel1.add(txt_estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 530, 240, 30));

        btn_agregar.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        btn_agregar.setText("AGREGAR");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 670, 140, 40));

        btn_eliminar.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        btn_eliminar.setText("ELIMINAR");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 670, 140, 40));

        btn_editar.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        btn_editar.setText("EDITAR");
        jPanel1.add(btn_editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 730, 140, 40));

        jLabel9.setFont(new java.awt.Font("Segoe UI Historic", 0, 36)); // NOI18N
        jLabel9.setText("MANTENIMIENTO CLIENTE");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, -1, -1));

        tb_cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "IdCliente", "Nombre", "Apellido", "DNI", "Telefono", "Dirección", "Estado", "Ruc Cliente", "Title 9"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tb_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_clienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_cliente);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, 930, 610));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1700, 840));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        // TODO add your handling code here:
        if ("".equals(txt_id.getText()) || !"".equals(txt_nombre.getText()) || !"".equals(txt_apellido.getText()) || !"".equals(txt_dni.getText())
        || !"".equals(txt_telefono.getText()) || !"".equals(txt_direccion.getText()) || !"".equals(txt_estado.getText()) || !"".equals(txt_ruc.getText())) {
           pro.setIdCliente(txt_id.getText());
           pro.setNombre(txt_nombre.getText());
           pro.setApellido(txt_apellido.getText());
           pro.setDNI(Integer.parseInt(txt_dni.getText()));
           pro.setTelefono(txt_telefono.getText());
           pro.setDireccion(txt_direccion.getText());
           pro.setEstado(txt_estado.getText());
           pro.setRuc_cliente(txt_ruc.getText());
           
           proDao.AgregarCliente(pro);
           JOptionPane.showMessageDialog(null, "PRODUCTO AGREGADO");
           LimpiarTabla();
           Listaclientes();
           //Limpiarproductos();
          
        }else{
            JOptionPane.showMessageDialog(null, "ESTAN VACIOS");
            
        }
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        // TODO add your handling code here:
        if(!"".equals(txt_id.getText())){
            int pregunta=JOptionPane.showConfirmDialog(null, "ESTA SEGURO QUE QUIERES ELIMINAR");
            if(pregunta==0){
                
                proDao.ElimarProducto(txt_id.getText());
                
                LimpiarTabla();
                Listaclientes();

            }
        }
        
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void tb_clienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_clienteMouseClicked
        // TODO add your handling code here:
        int fila = tb_cliente.rowAtPoint(evt.getPoint());
        txt_nombre.setText(tb_cliente.getValueAt(fila, 1).toString());
        txt_id.setText(tb_cliente.getValueAt(fila, 0).toString());
        txt_apellido.setText(tb_cliente.getValueAt(fila, 2).toString());
        txt_dni.setText(tb_cliente.getValueAt(fila, 3).toString());
        txt_telefono.setText(tb_cliente.getValueAt(fila, 4).toString());
        txt_direccion.setText(tb_cliente.getValueAt(fila, 5).toString());
        txt_estado.setText(tb_cliente.getValueAt(fila, 6).toString());
        txt_ruc.setText(tb_cliente.getValueAt(fila, 7).toString());
        
    }//GEN-LAST:event_tb_clienteMouseClicked
    public void LimpiarTabla(){
        for (int i = 0; i < tb_cliente.getRowCount(); i++) {
            modelo.removeRow(i);
            i=i-1;
            
        }
    }
    
    public void Listaclientes() {
        List<Cliente> Listacli = proDao.ListadeClientes();
        modelo = (DefaultTableModel) tb_cliente.getModel();
        Object[] ob = new Object[13];
        for (int i = 0; i < Listacli.size(); i++) {
            ob[0] = Listacli.get(i).getIdCliente();
            ob[1] = Listacli.get(i).getNombre();
            ob[2] = Listacli.get(i).getApellido();
            ob[3] = Listacli.get(i).getDNI();
            ob[4] = Listacli.get(i).getTelefono();
            ob[5] = Listacli.get(i).getDireccion();
            ob[6] = Listacli.get(i).getEstado();
            ob[7] = Listacli.get(i).getRuc_cliente();
            modelo.addRow(ob);
        }
        tb_cliente.setModel(modelo);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_cliente;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_dni;
    private javax.swing.JTextField txt_estado;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_ruc;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables
}
