/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Paneles;

import Clases.Producto;
import FuncionamientoTablas.TablaProductos;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author EDU
 */
public class Productos extends javax.swing.JPanel {
    Producto pro=new Producto();
    TablaProductos proDao=new TablaProductos();
    DefaultTableModel modelo = new DefaultTableModel();

    public Productos() {
        initComponents();
        Listaproductos();
        txt_fecha.setMinSelectableDate(new Date());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        txt_codigo = new javax.swing.JTextField();
        txt_preciocosto = new javax.swing.JTextField();
        txt_Stock = new javax.swing.JTextField();
        cb_talla = new javax.swing.JComboBox<>();
        txt_imagen = new javax.swing.JTextField();
        txt_Stockmin = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btn_Eliminar = new javax.swing.JButton();
        cb_categoria = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btn_agregar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        chb_promocion = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_precioventa = new javax.swing.JTextField();
        txt_color = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        imagen = new javax.swing.JLabel();
        txt_fecha = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cb_sexo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaListaPro = new javax.swing.JTable();

        jButton5.setText("Nuevo");

        cb_talla.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "S", "L", "XXL" }));

        txt_imagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_imagenActionPerformed(evt);
            }
        });

        jLabel4.setText("Talla");

        btn_Eliminar.setText("Eliminar");
        btn_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EliminarActionPerformed(evt);
            }
        });

        cb_categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Polos", "Pantalones", "Casacas", "Camisas", "Buzos", "Zapatos" }));

        jLabel5.setText("Stock");

        jLabel3.setText("sexo:");

        jButton1.setText("Examinar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btn_agregar.setText("Agregar");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });

        jLabel11.setText("Fecha:");

        chb_promocion.setText("Promocion");

        jLabel7.setText("Precio Costo");

        jLabel1.setText("Codigo:");

        jLabel2.setText("Nombre:");

        imagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel9.setText("Color");

        jButton3.setText("Editar");

        jLabel8.setText("Precio Venta");

        jLabel10.setText("Categoria:");

        cb_sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hombre", "Mujer" }));

        jLabel6.setText("Stock Minimo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(txt_color, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cb_talla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txt_Stock, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(52, 52, 52)
                                            .addComponent(jLabel6)
                                            .addGap(18, 18, 18))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addGap(9, 9, 9)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_precioventa, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt_Stockmin, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(26, 26, 26)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cb_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(chb_promocion))
                                        .addGap(328, 328, 328)))
                                .addComponent(txt_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(93, 93, 93))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(195, 195, 195)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cb_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_preciocosto, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(235, 235, 235)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(txt_imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jButton1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(666, 666, 666))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_agregar)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(btn_Eliminar))
                .addGap(794, 794, 794))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(182, 182, 182)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(cb_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel4)
                                            .addComponent(cb_talla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(cb_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txt_Stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(txt_Stockmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(txt_preciocosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_precioventa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(64, 64, 64)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(txt_imagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(26, 26, 26)
                        .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(chb_promocion)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_agregar)
                    .addComponent(btn_Eliminar))
                .addGap(194, 194, 194))
        );

        jTabbedPane1.addTab("tab1", jPanel1);

        TablaListaPro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Categoria", "Talla", "Stock", "Stock Minimo", "Precio compra", "Precio Venta", "Imagen", "Color", "Promocion", "Fecha", "Sexo"
            }
        ));
        TablaListaPro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaListaProMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaListaPro);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1043, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(633, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab2", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1730, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        // TODO add your handling code here:
        if ("".equals(txt_codigo.getText())|| !"".equals(txt_nombre.getText())|| !"".equals(txt_Stock.getText())|| !"".equals(txt_Stockmin.getText())
                || !"".equals(txt_preciocosto.getText())|| !"".equals(txt_precioventa.getText())|| !"".equals(txt_color.getText())|| !"".equals(txt_imagen.getText())) {
           pro.setCodigo(txt_codigo.getText());
           pro.setNombre(txt_nombre.getText());
           String selecionCategoria = (String) cb_categoria.getSelectedItem();
           pro.setCategoria(selecionCategoria);
           String selecionSexo = (String) cb_sexo.getSelectedItem();
           pro.setSexo(selecionSexo);
           String seleciontalla = (String) cb_talla.getSelectedItem();
           pro.setTalla(seleciontalla);
           pro.setStock(Integer.parseInt(txt_Stock.getText()));
           pro.setStockmin(Integer.parseInt(txt_Stockmin.getText()));
           pro.setPreciocom(Double.parseDouble(txt_preciocosto.getText()));
           pro.setPreciovent(Double.parseDouble(txt_precioventa.getText()));
           String rutaimagen = txt_imagen.getText(); 
           File file = new File(rutaimagen); 

           if (file.exists()) {
               try (FileInputStream fis = new FileInputStream(file)) {
                   byte[] fotoBytes = new byte[(int) file.length()];
                   fis.read(fotoBytes);
                   pro.setImagen(fotoBytes);
            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(this, "Archivo no encontrado");
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(this, "Error al leer el archivo de imagen");
                    }
               
           }
           pro.setColor((txt_color.getText()));
           pro.setPromocion(chb_promocion.isSelected());
           java.util.Date fecha = txt_fecha.getDate(); 
           if (fecha != null) {
    // Validar si la fecha es válida (no es una fecha pasada)
    if (fecha.after(new Date()) || fecha.equals(new Date())) {
        // Formatear la fecha si es válida
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        String fechaString = sdf.format(fecha); 
        pro.setFecha(fechaString);  // Establecer la fecha en el objeto Producto
    } else {
        JOptionPane.showMessageDialog(this, "La fecha seleccionada no es válida. Por favor, seleccione una fecha futura.", "Error", JOptionPane.ERROR_MESSAGE);
    }
}
           //pro.setFecha(txt_fecha.getDateFormatString());
           proDao.AgregarProductos(pro);
           JOptionPane.showMessageDialog(null, "PRODUCTO AGREGADO");
           LimpiarTabla();
           Listaproductos();
           //Limpiarproductos();
          
        }else{
            JOptionPane.showMessageDialog(null, "ESTAN VACIOS");
            
        }
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        FileNameExtensionFilter filtro=new FileNameExtensionFilter("Formatos de Archivos JPEG(*.JPG;.*JPEG)","jpg","jpeg");
        JFileChooser archivo=new JFileChooser();
        archivo.addChoosableFileFilter(filtro);
        archivo.setDialogTitle("Abrir Archivo");
        File ruta= new File("D:/");//para que aparesca la ruta
        archivo.setCurrentDirectory(ruta);
        
        int ventana =archivo.showOpenDialog(null);
        if (ventana== JFileChooser.APPROVE_OPTION) {
            File file=archivo.getSelectedFile();
            txt_imagen.setText(String.valueOf(file));
            Image foto=getToolkit().createImage(txt_imagen.getText());
            foto=foto.getScaledInstance(110, 110, Image.SCALE_DEFAULT);
            imagen.setIcon(new ImageIcon(foto));
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_imagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_imagenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_imagenActionPerformed

    private void TablaListaProMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaListaProMouseClicked
        // TODO add your handling code here:
        int fila = TablaListaPro.rowAtPoint(evt.getPoint());
        txt_nombre.setText(TablaListaPro.getValueAt(fila, 1).toString());
        txt_codigo.setText(TablaListaPro.getValueAt(fila, 0).toString());
        txt_Stock.setText(TablaListaPro.getValueAt(fila, 4).toString());
        txt_preciocosto.setText(TablaListaPro.getValueAt(fila, 6).toString());
        txt_precioventa.setText(TablaListaPro.getValueAt(fila, 7).toString());
        txt_Stockmin.setText(TablaListaPro.getValueAt(fila, 5).toString());
        txt_color.setText(TablaListaPro.getValueAt(fila, 9).toString());
        
        byte[] imagenBytes = (byte[]) TablaListaPro.getValueAt(fila, 8); 
        //txt_imagen.setText(TablaListaPro.getValueAt(fila,8));
        if (imagenBytes != null) {
         ImageIcon icon = new ImageIcon(imagenBytes);
         Image img = icon.getImage();  
          Image newImg = img.getScaledInstance(100, 100,  java.awt.Image.SCALE_SMOOTH);
          icon = new ImageIcon(newImg);
          imagen.setIcon(icon);
        }
        String categoria = TablaListaPro.getValueAt(fila, 2).toString(); 
        String talla = TablaListaPro.getValueAt(fila, 3).toString();
        String sexo=TablaListaPro.getValueAt(fila, 12).toString();
        cb_categoria.setSelectedItem(categoria);
        cb_talla.setSelectedItem(talla);
        cb_sexo.setSelectedItem(sexo);
        boolean promocion = (boolean) TablaListaPro.getValueAt(fila, 10); 
        chb_promocion.setSelected(promocion);
        String fechaCaducidad = TablaListaPro.getValueAt(fila, 11).toString();
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy"); // Ajusta el formato si es necesario
        try {
            Date fecha = sdf.parse(fechaCaducidad);
            txt_fecha.setDate(fecha); 
        } catch (ParseException e) {
            e.printStackTrace();
    }
        
        

        
        
    }//GEN-LAST:event_TablaListaProMouseClicked

    private void btn_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EliminarActionPerformed
        // TODO add your handling code here:
        if(!"".equals(txt_codigo.getText())){
            int pregunta=JOptionPane.showConfirmDialog(null, "ESTA SEGURO QUE QUIERES ELIMINAR");
            if(pregunta==0){
                
                proDao.ElimarProducto(txt_codigo.getText());
                
                LimpiarTabla();
                Listaproductos();
                
                
                
            }
        }
        
    }//GEN-LAST:event_btn_EliminarActionPerformed
public void Listaproductos() {
        List<Producto> Listapro = proDao.ListadeProductos();
        modelo = (DefaultTableModel) TablaListaPro.getModel();
        Object[] ob = new Object[13];
        for (int i = 0; i < Listapro.size(); i++) {
            ob[0] = Listapro.get(i).getCodigo();
            ob[1] = Listapro.get(i).getNombre();
            ob[2] = Listapro.get(i).getCategoria();
            ob[3] = Listapro.get(i).getTalla();
            ob[4] = Listapro.get(i).getStock();
            ob[5] = Listapro.get(i).getStockmin();
            ob[6] = Listapro.get(i).getPreciocom();
            ob[7] = Listapro.get(i).getPreciovent();
            ob[8] = Listapro.get(i).getImagen();
            ob[9] = Listapro.get(i).getColor();
            ob[10] = Listapro.get(i).isPromocion();
            ob[11] = Listapro.get(i).getFecha();
            ob[12]=Listapro.get(i).getSexo();
            
            modelo.addRow(ob);
        }
        TablaListaPro.setModel(modelo);

    }
    public void LimpiarTabla(){
        for (int i = 0; i < TablaListaPro.getRowCount(); i++) {
            modelo.removeRow(i);
            i=i-1;
            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaListaPro;
    private javax.swing.JButton btn_Eliminar;
    private javax.swing.JButton btn_agregar;
    private javax.swing.JComboBox<String> cb_categoria;
    private javax.swing.JComboBox<String> cb_sexo;
    private javax.swing.JComboBox<String> cb_talla;
    private javax.swing.JCheckBox chb_promocion;
    private javax.swing.JLabel imagen;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txt_Stock;
    private javax.swing.JTextField txt_Stockmin;
    private javax.swing.JTextField txt_codigo;
    private javax.swing.JTextField txt_color;
    private com.toedter.calendar.JDateChooser txt_fecha;
    private javax.swing.JTextField txt_imagen;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_preciocosto;
    private javax.swing.JTextField txt_precioventa;
    // End of variables declaration//GEN-END:variables
}
