/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Paneles;

import Clases.Cuenta;
import Clases.Producto;
import FuncionamientoTablas.TablaCuenta;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author EQUIPO
 */
public class Usuario extends javax.swing.JPanel {

    /**
     * Creates new form Usuario
     */
    
    Cuenta pro=new Cuenta();
    TablaCuenta proDao=new TablaCuenta();
    DefaultTableModel modelo = new DefaultTableModel();
    
    public Usuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_correo = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        txt_apellido = new javax.swing.JTextField();
        txt_dni1 = new javax.swing.JTextField();
        txt_usuario1 = new javax.swing.JTextField();
        txt_clave = new javax.swing.JTextField();
        cbo_rol = new javax.swing.JComboBox<>();
        cbo_estado = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_usuarios = new javax.swing.JTable();
        btn_agregar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        imagen = new javax.swing.JLabel();
        btn_examinar = new javax.swing.JButton();
        txt_imagen = new javax.swing.JTextField();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Nombre");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("DNI");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setText("Mantenimiento Usuario");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Apellido");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Usuario");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Clave");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Correo");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Estado");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Rol");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 580, -1, -1));
        jPanel1.add(txt_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, 260, 30));
        jPanel1.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 260, 30));
        jPanel1.add(txt_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 260, 30));
        jPanel1.add(txt_dni1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 260, 30));
        jPanel1.add(txt_usuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 260, 30));
        jPanel1.add(txt_clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 260, 30));

        cbo_rol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Usuario" }));
        jPanel1.add(cbo_rol, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 580, 260, 30));

        cbo_estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        jPanel1.add(cbo_estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 510, 260, 30));

        tb_usuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellido", "DNI", "Usuario", "Clave", "Correo", "Estado", "Rol", "Foto"
            }
        ));
        tb_usuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_usuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_usuarios);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 100, 840, 540));

        btn_agregar.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        btn_agregar.setText("AGREGAR");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 660, 140, 40));

        btn_eliminar.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        btn_eliminar.setText("ELIMINAR");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 660, 140, 40));

        btn_editar.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        btn_editar.setText("EDITAR");
        jPanel1.add(btn_editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 730, 140, 40));

        imagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, 220, 220));

        btn_examinar.setText("EXAMINAR");
        btn_examinar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_examinarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_examinar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, -1, -1));
        jPanel1.add(txt_imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, 220, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        // TODO add your handling code here:
        if ("".equals(txt_nombre.getText()) || !"".equals(txt_apellido.getText()) || !"".equals(txt_dni1.getText()) || !"".equals(txt_usuario1.getText())
            || !"".equals(txt_clave.getText()) || !"".equals(txt_correo.getText())) {
            pro.setNombre(txt_nombre.getText());
            pro.setApellido(txt_apellido.getText());
            pro.setDni(Integer.parseInt(txt_dni1.getText()));
            pro.setUsuario(txt_usuario1.getText());
            pro.setClave(txt_clave.getText());
            pro.setCorreo(txt_correo.getText());
            String selecEs = (String) cbo_estado.getSelectedItem();
            pro.setEstado(selecEs);
            String selecRol = (String) cbo_rol.getSelectedItem();
            pro.setRol(selecRol);
            String rutaimagen = txt_imagen.getText(); 
            File file = new File(rutaimagen);
            if (file.exists()) {
               try (FileInputStream fis = new FileInputStream(file)) {
                   byte[] fotoBytes = new byte[(int) file.length()];
                   fis.read(fotoBytes);
                   pro.setFoto(fotoBytes);
            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(this, "Archivo no encontrado");
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(this, "Error al leer el archivo de imagen");
                    }
               
           }

            proDao.AgregarCuenta(pro);
            JOptionPane.showMessageDialog(null, "PRODUCTO AGREGADO");
            LimpiarTabla();
            Listacuentas();
            //Limpiarproductos();

        }else{
            JOptionPane.showMessageDialog(null, "ESTAN VACIOS");

        }
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        // TODO add your handling code here:
        if(!"".equals(txt_nombre.getText())){
            int pregunta=JOptionPane.showConfirmDialog(null, "ESTA SEGURO QUE QUIERES ELIMINAR");
            if(pregunta==0){
                
                proDao.ElimarCuenta(txt_nombre.getText());
                
                LimpiarTabla();
                Listacuentas();
                
                
                
            }
        }

    }//GEN-LAST:event_btn_eliminarActionPerformed
    
    public void Listacuentas() {
        List<Cuenta> Listapro = proDao.ListadeCuentas();
        modelo = (DefaultTableModel) tb_usuarios.getModel();
        Object[] ob = new Object[13];
        for (int i = 0; i < Listapro.size(); i++) {
            ob[0] = Listapro.get(i).getNombre();
            ob[1] = Listapro.get(i).getApellido();
            ob[2] = Listapro.get(i).getDni();
            ob[3] = Listapro.get(i).getUsuario();
            ob[4] = Listapro.get(i).getClave();
            ob[5] = Listapro.get(i).getCorreo();
            ob[6] = Listapro.get(i).getEstado();
            ob[7] = Listapro.get(i).getRol();
            ob[8] = Listapro.get(i).getFoto();
            
            
            modelo.addRow(ob);
        }
        tb_usuarios.setModel(modelo);

    }
    public void LimpiarTabla(){
        for (int i = 0; i < tb_usuarios.getRowCount(); i++) {
            modelo.removeRow(i);
            i=i-1;
            
        }
    }
    
    private void btn_examinarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_examinarActionPerformed
        // TODO add your handling code here:
        FileNameExtensionFilter filtro=new FileNameExtensionFilter("Formatos de Archivos JPEG(*.JPG;.*JPEG)","jpg","jpeg");
        JFileChooser archivo=new JFileChooser();
        archivo.addChoosableFileFilter(filtro);
        archivo.setDialogTitle("Abrir Archivo");
        File ruta= new File("D:/");//para que aparesca la ruta
        archivo.setCurrentDirectory(ruta);
        
        int ventana =archivo.showOpenDialog(null);
        if (ventana== JFileChooser.APPROVE_OPTION) {
            File file=archivo.getSelectedFile();
            txt_imagen.setText(String.valueOf(file));
            Image foto=getToolkit().createImage(txt_imagen.getText());
            foto=foto.getScaledInstance(110, 110, Image.SCALE_DEFAULT);
            imagen.setIcon(new ImageIcon(foto));
            
        }
    }//GEN-LAST:event_btn_examinarActionPerformed

    private void tb_usuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_usuariosMouseClicked
        // TODO add your handling code here:
        int fila = tb_usuarios.rowAtPoint(evt.getPoint());
        txt_nombre.setText(tb_usuarios.getValueAt(fila, 0).toString());
        txt_apellido.setText(tb_usuarios.getValueAt(fila, 1).toString());
        txt_dni1.setText(tb_usuarios.getValueAt(fila, 2).toString());
        txt_usuario1.setText(tb_usuarios.getValueAt(fila, 3).toString());
        txt_clave.setText(tb_usuarios.getValueAt(fila, 4).toString());
        txt_correo.setText(tb_usuarios.getValueAt(fila, 5).toString());
        
        
        byte[] imagenBytes = (byte[]) tb_usuarios.getValueAt(fila, 8); 
        //txt_imagen.setText(TablaListaPro.getValueAt(fila,8));
        if (imagenBytes != null) {
         ImageIcon icon = new ImageIcon(imagenBytes);
         Image img = icon.getImage();  
          Image newImg = img.getScaledInstance(100, 100,  java.awt.Image.SCALE_SMOOTH);
          icon = new ImageIcon(newImg);
          imagen.setIcon(icon);
        }
        String estado = tb_usuarios.getValueAt(fila, 6).toString(); 
        String rol  = tb_usuarios.getValueAt(fila, 7).toString();
        
        cbo_estado.setSelectedItem(estado);
        cbo_rol.setSelectedItem(rol);
        
    }//GEN-LAST:event_tb_usuariosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_examinar;
    private javax.swing.JComboBox<String> cbo_estado;
    private javax.swing.JComboBox<String> cbo_rol;
    private javax.swing.JLabel imagen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_usuarios;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextField txt_clave;
    private javax.swing.JTextField txt_correo;
    private javax.swing.JTextField txt_dni1;
    private javax.swing.JTextField txt_imagen;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_usuario1;
    // End of variables declaration//GEN-END:variables
}
